<a href="https://colab.research.google.com/github/KunalSingh2/KunalSingh2/blob/main/Data%20Centre%20Knowledge%20Assistant.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install -q boto3

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.5/15.5 MB 71.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.2/90.2 kB 7.9 MB/s eta 0:00:00

In [2]:
import boto3
import json
import os

In [3]:
print("✅ boto3 imported successfully")
print("✅ json imported successfully")
print("✅ os imported successfully")

✅ boto3 imported successfully
✅ json imported successfully
✅ os imported successfully

In [8]:
import os

os.environ["AWS_DEFAULT_REGION"] = "ap-southeast-6"

print("Region loaded:", os.environ["AWS_DEFAULT_REGION"])

Region loaded: ap-southeast-6

In [10]:
from google.colab import userdata
import os

os.environ["AWS_ACCESS_KEY_ID"] = userdata.get("AWS_ACCESS_KEY_ID")
os.environ["AWS_SECRET_ACCESS_KEY"] = userdata.get("AWS_SECRET_ACCESS_KEY")
os.environ["AWS_DEFAULT_REGION"] = "ap-southeast-6"

print("Access key loaded:", bool(os.environ.get("AWS_ACCESS_KEY_ID")))
print("Secret key loaded:", bool(os.environ.get("AWS_SECRET_ACCESS_KEY")))
print("Region:", os.environ.get("AWS_DEFAULT_REGION"))

Access key loaded: True
Secret key loaded: True
Region: ap-southeast-6

In [11]:
import boto3

bedrock = boto3.client(
    service_name="bedrock-runtime",
    region_name=os.environ["AWS_DEFAULT_REGION"],
    aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"]
)

print("Bedrock client created successfully")
print("Region:", bedrock.meta.region_name)

Bedrock client created successfully
Region: ap-southeast-6

In [ ]:
import boto3
import os

bedrock = boto3.client(
    service_name="bedrock-runtime",
    region_name=os.environ["AWS_DEFAULT_REGION"],
    aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"]
)

print("✅ Amazon Bedrock client created successfully!")

✅ Amazon Bedrock client created successfully!

In [12]:
print("Bedrock Runtime region:", bedrock.meta.region_name)

Bedrock Runtime region: ap-southeast-6

In [13]:
print(bedrock.meta.region_name)

ap-southeast-6

In [14]:
import boto3

bedrock = boto3.client(
    service_name="bedrock-runtime",
    region_name="ap-southeast-6"
)

print(bedrock.meta.region_name)

ap-southeast-6

In [15]:
print(bedrock.meta.region_name)

ap-southeast-6

In [16]:
import boto3
import os

bedrock = boto3.client(
    service_name="bedrock-runtime",
    region_name="ap-southeast-6",
    aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"]
)

print("Region:", bedrock.meta.region_name)

Region: ap-southeast-6

In [17]:
import boto3
import os

bedrock_control = boto3.client(
    service_name="bedrock",
    region_name="ap-southeast-6",
    aws_access_key_id=os.environ["AWS_ACCESS_KEY_ID"],
    aws_secret_access_key=os.environ["AWS_SECRET_ACCESS_KEY"]
)

response = bedrock_control.list_inference_profiles(
    typeEquals="SYSTEM_DEFINED"
)

print("Available inference profiles:\n")

for profile in response.get("inferenceProfileSummaries", []):
    print("Name:", profile["inferenceProfileName"])
    print("ID:", profile["inferenceProfileId"])
    print("ARN:", profile["inferenceProfileArn"])
    print("Status:", profile["status"])
    print("-" * 60)

Available inference profiles:

Name: Global Nova 2 Lite
ID: global.amazon.nova-2-lite-v1:0
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.amazon.nova-2-lite-v1:0
Status: ACTIVE
------------------------------------------------------------
Name: AU Anthropic Claude Haiku 4.5
ID: au.anthropic.claude-haiku-4-5-20251001-v1:0
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/au.anthropic.claude-haiku-4-5-20251001-v1:0
Status: ACTIVE
------------------------------------------------------------
Name: AU Anthropic Claude Sonnet 4.6
ID: au.anthropic.claude-sonnet-4-6
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/au.anthropic.claude-sonnet-4-6
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Sonnet 4.6
ID: global.anthropic.claude-sonnet-4-6
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-sonnet-4-6
Status: ACTIVE
------------------------------------------------------------
Name: AU Anthropic Claude Opus 4.6
ID: au.anthropic.claude-opus-4-6-v1
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/au.anthropic.claude-opus-4-6-v1
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Opus 4.5
ID: global.anthropic.claude-opus-4-5-20251101-v1:0
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-opus-4-5-20251101-v1:0
Status: ACTIVE
------------------------------------------------------------
Name: AU Anthropic Claude Sonnet 4.5
ID: au.anthropic.claude-sonnet-4-5-20250929-v1:0
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/au.anthropic.claude-sonnet-4-5-20250929-v1:0
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Opus 4.6
ID: global.anthropic.claude-opus-4-6-v1
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-opus-4-6-v1
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Sonnet 4.5
ID: global.anthropic.claude-sonnet-4-5-20250929-v1:0
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-sonnet-4-5-20250929-v1:0
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Opus 4.7
ID: global.anthropic.claude-opus-4-7
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-opus-4-7
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Opus 4.8
ID: global.anthropic.claude-opus-4-8
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-opus-4-8
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Fable 5
ID: global.anthropic.claude-fable-5
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-fable-5
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Haiku 4.5
ID: global.anthropic.claude-haiku-4-5-20251001-v1:0
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-haiku-4-5-20251001-v1:0
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Sonnet 5
ID: global.anthropic.claude-sonnet-5
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-sonnet-5
Status: ACTIVE
------------------------------------------------------------
Name: Global Anthropic Claude Opus 5
ID: global.anthropic.claude-opus-5
ARN: arn:aws:bedrock:ap-southeast-6:433289389339:inference-profile/global.anthropic.claude-opus-5
Status: ACTIVE
------------------------------------------------------------

In [18]:
response = bedrock.converse(
    modelId="au.anthropic.claude-sonnet-4-6",
    messages=[
        {
            "role": "user",
            "content": [
                {
                    "text": "Hello! Please introduce yourself in one sentence."
                }
            ]
        }
    ],
    inferenceConfig={
        "maxTokens": 200,
        "temperature": 0.7
    }
)

claude_reply = response["output"]["message"]["content"][0]["text"]

print("Claude response:")
print(claude_reply)

Claude response:
Hello! I'm Claude, an AI assistant made by Anthropic, here to help you with questions, analysis, writing, coding, and much more.

In [19]:
region_name="ap-southeast-6"

In [20]:
!pip install -q pymupdf pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.7/25.7 MB 73.0 MB/s eta 0:00:00

In [21]:
import fitz
import pandas as pd
import os

In [22]:
pdf_files = [
    file_name
    for file_name in os.listdir("/content")
    if file_name.lower().endswith(".pdf")
]

print("PDF files found:", len(pdf_files))

for file_name in pdf_files:
    print("-", file_name)

PDF files found: 10
- SOP-MNT-003 Generator Monthly Inspection.pdf
- SOP-INC-003 Power Outage Procedure.pdf
- SOP-SHF-001 Day Shift Handover.pdf
- SOP-DC-002 Data Centre Shutdown.pdf
- SOP-MNT-001 UPS Preventive Maintenance.pdf
- SOP-SHF-002 Night Shift Handover.pdf
- SOP-MNT-002 Cooling System Maintenance.pdf
- SOP-DC-001 Data Centre Startup.pdf
- SOP-INC-002 Water Leak Response.pdf
- SOP-INC-001 Fire Incident Response.pdf

In [23]:
extracted_pages = []

for file_name in pdf_files:
    file_path = os.path.join("/content", file_name)

    with fitz.open(file_path) as pdf_document:
        for page_number, page in enumerate(pdf_document, start=1):
            page_text = page.get_text("text").strip()

            extracted_pages.append(
                {
                    "source_file": file_name,
                    "page_number": page_number,
                    "text": page_text,
                    "character_count": len(page_text)
                }
            )

print("Total pages extracted:", len(extracted_pages))

Total pages extracted: 20

In [24]:
pages_df = pd.DataFrame(extracted_pages)

pages_df.head()

,source_file,page_number,text,character_count
0,SOP-MNT-003 Generator Monthly Inspection.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1265
1,SOP-MNT-003 Generator Monthly Inspection.pdf,2,"1. Fluid Levels Check: Inspect fuel, oil, and ...",1938
2,SOP-INC-003 Power Outage Procedure.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1174
3,SOP-INC-003 Power Outage Procedure.pdf,2,1. Detection & Verification: Confirm grid loss...,1681
4,SOP-SHF-001 Day Shift Handover.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1275

In [25]:
pages_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   source_file      20 non-null     object
 1   page_number      20 non-null     int64
 2   text             20 non-null     object
 3   character_count  20 non-null     int64
dtypes: int64(2), object(2)
memory usage: 772.0+ bytes

In [26]:
pages_df.describe(include="all")

,source_file,page_number,text,character_count
count,20,20.000000,20,20.000000
unique,10,NaN,20,NaN
top,SOP-MNT-003 Generator Monthly Inspection.pdf,NaN,AETHELGARD DATA CENTRE \nStandard Operating Pr...,NaN
freq,2,NaN,1,NaN
mean,NaN,1.500000,NaN,1476.650000
std,NaN,0.512989,NaN,266.688124
min,NaN,1.000000,NaN,1174.000000
25%,NaN,1.000000,NaN,1232.250000
50%,NaN,1.500000,NaN,1374.000000
75%,NaN,2.000000,NaN,1706.500000
max,NaN,2.000000,NaN,1938.000000

In [27]:
empty_pages = pages_df[pages_df["character_count"] == 0]

print("Empty pages:", len(empty_pages))

empty_pages

Empty pages: 0

Empty DataFrame
Columns: [source_file, page_number, text, character_count]
Index: []

In [28]:
print(pages_df.loc[0, "text"][:1000])

AETHELGARD DATA CENTRE
Standard Operating Procedure (SOP)
Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic
Node (Svalbard)
•
Document ID: SOP-MNT-003
•
Document Title: Generator Monthly Inspection
•
Version: 1.0
•
Department: Facilities Team
•
Classification: Internal
•
Author: Kaho Operations Team
•
Approved By: Data Centre Manager
•
Effective Date: 01-Aug-2026
•
Review Date: 01-Aug-2027
1. Purpose
To perform comprehensive monthly inspections of backup diesel generators, ensuring
immediate, reliable power availability during primary grid failure events.
2. Scope
Applies to all primary and secondary backup diesel generator sets, Automatic Transfer
Switches (ATS), and associated fuel storage systems within the Aethelgard Arctic Node.
3. Responsibilities
•
Operations Engineer
•
Lead Facilities Engineer
•
On-Duty Facilities Engineer
4. Safety Precautions
•
Wear appropriate PPE (hearing protection, eye protection, sa

In [30]:
!pip install -q sentence-transformers

In [31]:
import re
import pandas as pd
from sentence_transformers import SentenceTransformer

In [32]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print("✅ Model loaded successfully!")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 90.9MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

✅ Model loaded successfully!

In [33]:
print("Total pages:", len(pages_df))
pages_df.head()

Total pages: 20

,source_file,page_number,text,character_count
0,SOP-MNT-003 Generator Monthly Inspection.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1265
1,SOP-MNT-003 Generator Monthly Inspection.pdf,2,"1. Fluid Levels Check: Inspect fuel, oil, and ...",1938
2,SOP-INC-003 Power Outage Procedure.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1174
3,SOP-INC-003 Power Outage Procedure.pdf,2,1. Detection & Verification: Confirm grid loss...,1681
4,SOP-SHF-001 Day Shift Handover.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1275

In [34]:
def clean_text(text):
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

pages_df["clean_text"] = pages_df["text"].apply(clean_text)

pages_df.head()

,source_file,page_number,text,character_count,clean_text
0,SOP-MNT-003 Generator Monthly Inspection.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1265,AETHELGARD DATA CENTRE Standard Operating Proc...
1,SOP-MNT-003 Generator Monthly Inspection.pdf,2,"1. Fluid Levels Check: Inspect fuel, oil, and ...",1938,"1. Fluid Levels Check: Inspect fuel, oil, and ..."
2,SOP-INC-003 Power Outage Procedure.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1174,AETHELGARD DATA CENTRE Standard Operating Proc...
3,SOP-INC-003 Power Outage Procedure.pdf,2,1. Detection & Verification: Confirm grid loss...,1681,1. Detection & Verification: Confirm grid loss...
4,SOP-SHF-001 Day Shift Handover.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1275,AETHELGARD DATA CENTRE Standard Operating Proc...

In [35]:
def clean_text(text):
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()

pages_df["clean_text"] = pages_df["text"].apply(clean_text)

pages_df.head()

,source_file,page_number,text,character_count,clean_text
0,SOP-MNT-003 Generator Monthly Inspection.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1265,AETHELGARD DATA CENTRE Standard Operating Proc...
1,SOP-MNT-003 Generator Monthly Inspection.pdf,2,"1. Fluid Levels Check: Inspect fuel, oil, and ...",1938,"1. Fluid Levels Check: Inspect fuel, oil, and ..."
2,SOP-INC-003 Power Outage Procedure.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1174,AETHELGARD DATA CENTRE Standard Operating Proc...
3,SOP-INC-003 Power Outage Procedure.pdf,2,1. Detection & Verification: Confirm grid loss...,1681,1. Detection & Verification: Confirm grid loss...
4,SOP-SHF-001 Day Shift Handover.pdf,1,AETHELGARD DATA CENTRE \nStandard Operating Pr...,1275,AETHELGARD DATA CENTRE Standard Operating Proc...

In [36]:
print(pages_df.loc[0, "clean_text"][:1000])

AETHELGARD DATA CENTRE Standard Operating Procedure (SOP) Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic Node (Svalbard) • Document ID: SOP-MNT-003 • Document Title: Generator Monthly Inspection • Version: 1.0 • Department: Facilities Team • Classification: Internal • Author: Kaho Operations Team • Approved By: Data Centre Manager • Effective Date: 01-Aug-2026 • Review Date: 01-Aug-2027 1. Purpose To perform comprehensive monthly inspections of backup diesel generators, ensuring immediate, reliable power availability during primary grid failure events. 2. Scope Applies to all primary and secondary backup diesel generator sets, Automatic Transfer Switches (ATS), and associated fuel storage systems within the Aethelgard Arctic Node. 3. Responsibilities • Operations Engineer • Lead Facilities Engineer • On-Duty Facilities Engineer 4. Safety Precautions • Wear appropriate PPE (hearing protection, eye protection, safety gloves). • Follow Lockout/Tagout

In [38]:
def create_chunks(text, chunk_size=700, overlap=100):
    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size
        chunk = text[start:end]

        chunks.append(chunk)

        start += chunk_size - overlap

    return chunks

In [39]:
chunk_records = []

for _, row in pages_df.iterrows():

    chunks = create_chunks(row["clean_text"])

    for i, chunk in enumerate(chunks):

        chunk_records.append({
            "source_file": row["source_file"],
            "page_number": row["page_number"],
            "chunk_number": i + 1,
            "chunk_text": chunk
        })

chunks_df = pd.DataFrame(chunk_records)

print("Total Chunks:", len(chunks_df))

chunks_df.head()

Total Chunks: 56

,source_file,page_number,chunk_number,chunk_text
0,SOP-MNT-003 Generator Monthly Inspection.pdf,1,1,AETHELGARD DATA CENTRE Standard Operating Proc...
1,SOP-MNT-003 Generator Monthly Inspection.pdf,1,2,Scope Applies to all primary and secondary ba...
2,SOP-MNT-003 Generator Monthly Inspection.pdf,1,3,visor. 5. Procedures
3,SOP-MNT-003 Generator Monthly Inspection.pdf,2,1,"1. Fluid Levels Check: Inspect fuel, oil, and ..."
4,SOP-MNT-003 Generator Monthly Inspection.pdf,2,2,eshold: No visual damage or ice accumulation. ...

In [40]:
embeddings = model.encode(
    chunks_df["chunk_text"].tolist(),
    show_progress_bar=True,
    convert_to_numpy=True
)

print("Embedding Shape:", embeddings.shape)

Batches:   0%|          | 0/2 [00:00<?, ?it/s]

Embedding Shape: (56, 384)

In [41]:
!pip install -q faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 32.9 MB/s eta 0:00:00

In [42]:
import faiss
import numpy as np

In [43]:
dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(embeddings)

print("FAISS Index Created Successfully!")
print("Total Vectors:", index.ntotal)

FAISS Index Created Successfully!
Total Vectors: 56

In [44]:
def search_documents(query, top_k=3):
    # Convert the user query into an embedding
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    )

    # Search the FAISS index
    distances, indices = index.search(query_embedding, top_k)

    results = []

    for i in indices[0]:
        results.append(chunks_df.iloc[i])

    return pd.DataFrame(results)

In [45]:
query = "What should I do during a power outage?"

results = search_documents(query)

results

,source_file,page_number,chunk_number,chunk_text
7,SOP-INC-003 Power Outage Procedure.pdf,1,1,AETHELGARD DATA CENTRE Standard Operating Proc...
24,SOP-MNT-001 UPS Preventive Maintenance.pdf,1,1,AETHELGARD DATA CENTRE Standard Operating Proc...
40,SOP-DC-001 Data Centre Startup.pdf,1,1,AETHELGARD DATA CENTRE Standard Operating Proc...

In [46]:
for i, row in results.iterrows():
    print("=" * 80)
    print(f"Source: {row['source_file']}")
    print(f"Page: {row['page_number']}")
    print()
    print(row["chunk_text"])
    print()

================================================================================
Source: SOP-INC-003 Power Outage Procedure.pdf
Page: 1

AETHELGARD DATA CENTRE Standard Operating Procedure (SOP) Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic Node (Svalbard) • Document ID: SOP-INC-003 • Document Title: Power Outage Procedure • Version: 1.0 • Department: Facilities Team • Classification: Internal • Author: Kaho Operations Team • Approved By: Data Centre Manager • Effective Date: 01-Aug-2026 • Review Date: 01-Aug-2027 1. Purpose To maintain site-wide operational continuity during a grid power failure by managing the seamless transition to backup diesel generation. 2. Scope Applies to the Automatic Transfer Switch (ATS), backup diesel generators, and critical load management systems within t

================================================================================
Source: SOP-MNT-001 UPS Preventive Maintenance.pdf
Page: 1

AETHELGARD DATA CENTRE Standard Operating Procedure (SOP) Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic Node (Svalbard) • Document ID: SOP-MNT-001 • Document Title: UPS Preventive Maintenance • Version: 1.0 • Department: Facilities Team • Classification: Internal • Author: Kaho Operations Team • Approved By: Data Centre Manager • Effective Date: 01-Aug-2026 • Review Date: 01-Aug-2027 1. Purpose To maintain the operational integrity of the Uninterruptible Power Supply (UPS) systems, ensuring reliable power protection for critical Aethelgard server loads. 2. Scope Applies to all UPS battery strings, inverter modules, and associated static switch gear wit

================================================================================
Source: SOP-DC-001 Data Centre Startup.pdf
Page: 1

AETHELGARD DATA CENTRE Standard Operating Procedure (SOP) Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic Node (Svalbard) • Document ID: SOP-DC-001 • Document Title: Data Centre Startup • Version: 1.0 • Department: Facilities Team • Classification: Internal • Author: Kaho Operations Team • Approved By: Data Centre Manager • Effective Date: 01-Aug-2026 • Review Date: 01-Aug-2027 1. Purpose To provide a controlled, systematic method for energizing the Aethelgard data centre infrastructure to ensure system stability and equipment longevity following a total site shutdown. 2. Scope Applies to all Power Distribution Units (PDU), Uninterruptible Power Supply (

In [47]:
def retrieve_context(query, top_k=3):
    query_embedding = model.encode(
        [query],
        convert_to_numpy=True
    )

    distances, indices = index.search(query_embedding, top_k)

    context = ""

    for idx in indices[0]:
        context += chunks_df.iloc[idx]["chunk_text"] + "\n\n"

    return context

In [48]:
query = "What should I do during a power outage?"

context = retrieve_context(query)

print(context)

AETHELGARD DATA CENTRE Standard Operating Procedure (SOP) Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic Node (Svalbard) • Document ID: SOP-INC-003 • Document Title: Power Outage Procedure • Version: 1.0 • Department: Facilities Team • Classification: Internal • Author: Kaho Operations Team • Approved By: Data Centre Manager • Effective Date: 01-Aug-2026 • Review Date: 01-Aug-2027 1. Purpose To maintain site-wide operational continuity during a grid power failure by managing the seamless transition to backup diesel generation. 2. Scope Applies to the Automatic Transfer Switch (ATS), backup diesel generators, and critical load management systems within t

AETHELGARD DATA CENTRE Standard Operating Procedure (SOP) Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic Node (Svalbard) • Document ID: SOP-MNT-001 • Document Title: UPS Preventive Maintenance • Version: 1.0 • Department: Facilities Team • Classification: Internal • Author: Kaho Operations Team • Approved By: Data Centre Manager • Effective Date: 01-Aug-2026 • Review Date: 01-Aug-2027 1. Purpose To maintain the operational integrity of the Uninterruptible Power Supply (UPS) systems, ensuring reliable power protection for critical Aethelgard server loads. 2. Scope Applies to all UPS battery strings, inverter modules, and associated static switch gear wit

AETHELGARD DATA CENTRE Standard Operating Procedure (SOP) Company: Kaho AI and Automation Consultancy Facility: Aethelgard Data Centre – Arctic Node (Svalbard) • Document ID: SOP-DC-001 • Document Title: Data Centre Startup • Version: 1.0 • Department: Facilities Team • Classification: Internal • Author: Kaho Operations Team • Approved By: Data Centre Manager • Effective Date: 01-Aug-2026 • Review Date: 01-Aug-2027 1. Purpose To provide a controlled, systematic method for energizing the Aethelgard data centre infrastructure to ensure system stability and equipment longevity following a total site shutdown. 2. Scope Applies to all Power Distribution Units (PDU), Uninterruptible Power Supply (

In [49]:
print(bedrock)

<botocore.client.BedrockRuntime object at 0x7ab12ddcb260>

In [50]:
def ask_claude(query):

    context = retrieve_context(query)

    prompt = f"""
You are an AI Data Centre Operations Assistant.

Answer ONLY using the information provided below.

If the answer is not contained in the context, reply:
"I could not find that information in the SOP documents."

========================
Context:
{context}
========================

Question:
{query}
"""

    response = bedrock.converse(
        modelId="au.anthropic.claude-sonnet-4-6",
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "text": prompt
                    }
                ]
            }
        ]
    )

    return response["output"]["message"]["content"][0]["text"]

In [51]:
question = "What should I do during a power outage?"

answer = ask_claude(question)

print(answer)

# Power Outage Procedure

Based on the SOP documents available, I can see that **SOP-INC-003** covers the **Power Outage Procedure** for the Aethelgard Data Centre (Arctic Node, Svalbard).

However, the full procedural steps from that document have **not been fully provided** in the context given to me — the content appears to be truncated.

---

## What I Can Confirm from the Available Context:

The Power Outage Procedure (SOP-INC-003) is designed to:

- ✅ **Maintain site-wide operational continuity** during a grid power failure
- ✅ **Manage the seamless transition to backup diesel generation**
- ✅ It covers the following systems:
  - **Automatic Transfer Switch (ATS)**
  - **Backup diesel generators**
  - **Critical load management systems**

---

## My Recommendation:

📄 Please refer directly to the **full SOP-INC-003 document** for the complete step-by-step power outage response procedure.

> If you can provide the remaining content of SOP-INC-003, I will be happy to give you a detailed answer based on the documented steps.

In [52]:
!pip install -q streamlit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 34.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 37.1 MB/s eta 0:00:00

In [53]:
from google.colab import userdata
import os

os.environ["AWS_ACCESS_KEY_ID"] = userdata.get("AWS_ACCESS_KEY_ID")
os.environ["AWS_SECRET_ACCESS_KEY"] = userdata.get("AWS_SECRET_ACCESS_KEY")
os.environ["AWS_DEFAULT_REGION"] = "ap-southeast-6"

print("✅ AWS environment configured")

✅ AWS environment configured

In [54]:
%%writefile app.py

import os
import glob
import re

import boto3
import faiss
import fitz
import numpy as np
import pandas as pd
import streamlit as st
from sentence_transformers import SentenceTransformer


# -----------------------------------------------------
# Page configuration
# -----------------------------------------------------

st.set_page_config(
    page_title="Data Centre Knowledge Assistant",
    page_icon="🏢",
    layout="wide"
)

st.title("🏢 Data Centre Knowledge Assistant")

st.write(
    "Ask questions about data centre procedures, incidents, "
    "maintenance, safety, handovers, and operational SOPs."
)


# -----------------------------------------------------
# Configuration
# -----------------------------------------------------

AWS_REGION = os.getenv("AWS_DEFAULT_REGION", "ap-southeast-6")
MODEL_ID = "au.anthropic.claude-sonnet-4-6"


# -----------------------------------------------------
# Text cleaning and chunking
# -----------------------------------------------------

def clean_text(text):
    text = text.replace("\n", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def create_chunks(text, chunk_size=700, overlap=100):
    chunks = []
    start = 0
    step = chunk_size - overlap

    while start < len(text):
        chunk = text[start:start + chunk_size].strip()

        if chunk:
            chunks.append(chunk)

        start += step

    return chunks


# -----------------------------------------------------
# Load documents and build FAISS index
# -----------------------------------------------------

@st.cache_resource
def load_knowledge_base():
    pdf_files = glob.glob("/content/*.pdf")

    if not pdf_files:
        raise FileNotFoundError(
            "No PDF files were found in /content. "
            "Upload the SOP PDFs to Colab first."
        )

    chunk_records = []

    for file_path in pdf_files:
        source_file = os.path.basename(file_path)

        with fitz.open(file_path) as pdf_document:
            for page_number, page in enumerate(pdf_document, start=1):
                page_text = clean_text(page.get_text("text"))

                for chunk_number, chunk in enumerate(
                    create_chunks(page_text),
                    start=1
                ):
                    chunk_records.append({
                        "source_file": source_file,
                        "page_number": page_number,
                        "chunk_number": chunk_number,
                        "chunk_text": chunk
                    })

    chunks_df = pd.DataFrame(chunk_records)

    embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

    embeddings = embedding_model.encode(
        chunks_df["chunk_text"].tolist(),
        convert_to_numpy=True,
        show_progress_bar=False
    ).astype("float32")

    dimension = embeddings.shape[1]

    faiss_index = faiss.IndexFlatL2(dimension)
    faiss_index.add(embeddings)

    return chunks_df, embedding_model, faiss_index


# -----------------------------------------------------
# Amazon Bedrock client
# -----------------------------------------------------

@st.cache_resource
def create_bedrock_client():
    return boto3.client(
        service_name="bedrock-runtime",
        region_name=AWS_REGION
    )


# -----------------------------------------------------
# Document retrieval
# -----------------------------------------------------

def retrieve_documents(
    question,
    chunks_df,
    embedding_model,
    faiss_index,
    top_k=5
):
    query_embedding = embedding_model.encode(
        [question],
        convert_to_numpy=True
    ).astype("float32")

    distances, indices = faiss_index.search(
        query_embedding,
        min(top_k, len(chunks_df))
    )

    retrieved_rows = []

    for position, chunk_index in enumerate(indices[0]):
        if chunk_index < 0:
            continue

        row = chunks_df.iloc[chunk_index]

        retrieved_rows.append({
            "source_file": row["source_file"],
            "page_number": int(row["page_number"]),
            "chunk_number": int(row["chunk_number"]),
            "chunk_text": row["chunk_text"],
            "distance": float(distances[0][position])
        })

    return retrieved_rows


# -----------------------------------------------------
# Claude RAG response
# -----------------------------------------------------

def ask_claude(question, retrieved_documents, bedrock_client):
    context_sections = []

    for document in retrieved_documents:
        context_sections.append(
            f"""
Source: {document["source_file"]}
Page: {document["page_number"]}
Content:
{document["chunk_text"]}
"""
        )

    context = "\n\n".join(context_sections)

    prompt = f"""
You are an AI Data Centre Operations Knowledge Assistant.

Answer the user's question using only the SOP context below.

Instructions:
- Do not invent procedures.
- Give clear and practical operational steps.
- Mention the relevant source document and page where possible.
- If the context does not contain enough information, say:
  "I could not find enough information in the available SOP documents."

SOP CONTEXT:
{context}

USER QUESTION:
{question}
"""

    response = bedrock_client.converse(
        modelId=MODEL_ID,
        messages=[
            {
                "role": "user",
                "content": [
                    {
                        "text": prompt
                    }
                ]
            }
        ],
        inferenceConfig={
            "maxTokens": 1000,
            "temperature": 0.1
        }
    )

    return response["output"]["message"]["content"][0]["text"]


# -----------------------------------------------------
# Load application resources
# -----------------------------------------------------

try:
    chunks_df, embedding_model, faiss_index = load_knowledge_base()
    bedrock_client = create_bedrock_client()

    st.success(
        f"Knowledge base ready: "
        f"{len(chunks_df)} searchable SOP chunks loaded."
    )

except Exception as error:
    st.error(f"Application setup failed: {error}")
    st.stop()


# -----------------------------------------------------
# User interface
# -----------------------------------------------------

question = st.text_input(
    "Ask a question",
    placeholder="Example: What should I do during a power outage?"
)

ask_button = st.button(
    "Ask the Assistant",
    type="primary"
)

if ask_button:
    if not question.strip():
        st.warning("Please enter a question.")

    else:
        with st.spinner("Searching SOP documents and consulting Claude..."):
            try:
                retrieved_documents = retrieve_documents(
                    question=question,
                    chunks_df=chunks_df,
                    embedding_model=embedding_model,
                    faiss_index=faiss_index,
                    top_k=5
                )

                answer = ask_claude(
                    question=question,
                    retrieved_documents=retrieved_documents,
                    bedrock_client=bedrock_client
                )

                st.subheader("Assistant response")
                st.markdown(answer)

                with st.expander("View retrieved SOP sources"):
                    for number, document in enumerate(
                        retrieved_documents,
                        start=1
                    ):
                        st.markdown(
                            f"""
**Result {number}**

- **Document:** {document["source_file"]}
- **Page:** {document["page_number"]}
- **Chunk:** {document["chunk_number"]}
"""
                        )

                        st.write(document["chunk_text"])
                        st.divider()

            except Exception as error:
                st.error(f"Unable to generate an answer: {error}")


# -----------------------------------------------------
# Footer
# -----------------------------------------------------

st.caption(
    "Built with Amazon Bedrock, Anthropic Claude, "
    "Sentence Transformers, FAISS, and Streamlit."
)

Writing app.py

In [55]:
!ls -lh app.py

-rw-r--r-- 1 root root 8.0K Jul 30 23:05 app.py

In [56]:
!python -m py_compile app.py

print("✅ Streamlit application file is valid")

✅ Streamlit application file is valid

In [57]:
!streamlit run app.py & npx localtunnel --port 8501

⠙⠹⠸⠼
Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

⠴⠦⠧Need to install the following packages:
localtunnel@2.0.2
Ok to proceed? (y) 2026-07-30 23:07:59.307 Uvicorn server started on :::8501

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.125.146.6:8501

  Stopping...
^C

In [58]:
!npm install -g localtunnel

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴
added 22 packages in 4s
⠦
⠦3 packages are looking for funding
⠦  run `npm fund` for details
⠦

In [59]:
!streamlit run app.py >/content/streamlit.log 2>&1 &

In [60]:
!lt --port 8501

your url is: https://fluffy-rats-jam.loca.lt
^C

In [66]:
!pkill -f streamlit

In [67]:
!streamlit run app.py \
  --server.port 8501 \
  --server.enableCORS false \
  --server.enableXsrfProtection false \
  --server.enableWebsocketCompression false \
  >/content/streamlit.log 2>&1 &

In [68]:
!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
  -O /usr/local/bin/cloudflared

!chmod +x /usr/local/bin/cloudflared

In [ ]:
!cloudflared tunnel --url http://localhost:8501

2026-07-30T23:19:09Z INF Thank you for trying Cloudflare Tunnel. Doing so, without a Cloudflare account, is a quick way to experiment and try it out. However, be aware that these account-less Tunnels have no uptime guarantee, are subject to the Cloudflare Online Services Terms of Use (https://www.cloudflare.com/website-terms/), and Cloudflare reserves the right to investigate your use of Tunnels for violations of such terms. If you intend to use Tunnels in production you should use a pre-created named tunnel by following: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps
2026-07-30T23:19:09Z INF Requesting new quick Tunnel on trycloudflare.com...
2026-07-30T23:19:12Z INF +--------------------------------------------------------------------------------------------+
2026-07-30T23:19:12Z INF |  Your quick Tunnel has been created! Visit it at (it may take some time to be reachable):  |
2026-07-30T23:19:12Z INF |  https://assumes-classified-fancy-discussed.trycloudflare.com                              |
2026-07-30T23:19:12Z INF +--------------------------------------------------------------------------------------------+
2026-07-30T23:19:12Z INF Cannot determine default configuration path. No file [config.yml config.yaml] in [~/.cloudflared ~/.cloudflare-warp ~/cloudflare-warp /etc/cloudflared /usr/local/etc/cloudflared]
2026-07-30T23:19:12Z INF Version 2026.7.3 (Checksum 9d71c677db00134c1bd4144b7783486b654ad281b1ea62b4972098d19f770f17)
2026-07-30T23:19:12Z INF GOOS: linux, GOVersion: go1.26.4, GoArch: amd64
2026-07-30T23:19:12Z INF Settings: map[ha-connections:1 protocol:quic url:http://localhost:8501]
2026-07-30T23:19:12Z INF cloudflared will not automatically update when run from the shell. To enable auto-updates, run cloudflared as a service: https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configure-tunnels/local-management/as-a-service/
2026-07-30T23:19:12Z INF Generated Connector ID: 3e053689-0e7c-446e-ad03-eaf7a545d00f
2026-07-30T23:19:12Z INF Initial protocol quic
2026-07-30T23:19:12Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-07-30T23:19:12Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026/07/30 23:19:12 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
2026-07-30T23:19:12Z INF ICMP proxy will use 172.28.0.12 as source for IPv4
2026-07-30T23:19:12Z INF ICMP proxy will use ::1 in zone lo as source for IPv6
2026-07-30T23:19:12Z INF Starting metrics server on 127.0.0.1:20241/metrics
2026-07-30T23:19:12Z INF Tunnel connection curve preferences: [X25519MLKEM768 CurveID(65074) CurveP256] connIndex=0 event=0 ip=198.41.192.67
2026-07-30T23:19:13Z INF Registered tunnel connection connIndex=0 connection=c59bb0cc-12e6-4b85-b308-0d1ff51387b9 event=0 ip=198.41.192.67 location=lax07 protocol=quic
2026-07-30T23:19:18Z INF +-------------------------------------------------------------------------------------+
2026-07-30T23:19:18Z INF |                               CONNECTIVITY PRE-CHECKS                               |
2026-07-30T23:19:18Z INF +-------------------------------------------------------------------------------------+
2026-07-30T23:19:18Z INF |  COMPONENT         TARGET                     STATUS  DETAILS                       |
2026-07-30T23:19:18Z INF |  DNS Resolution    region1.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-07-30T23:19:18Z INF |  DNS Resolution    region2.v2.argotunnel.com  PASS    DNS Resolved successfully     |
2026-07-30T23:19:18Z INF |  UDP Connectivity  region1.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-07-30T23:19:18Z INF |  UDP Connectivity  region2.v2.argotunnel.com  PASS    QUIC connection successful    |
2026-07-30T23:19:18Z INF |  TCP Connectivity  region1.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-07-30T23:19:18Z INF |  TCP Connectivity  region2.v2.argotunnel.com  PASS    HTTP/2 connection successful  |
2026-07-30T23:19:18Z INF |  Cloudflare API    api.cloudflare.com:443     PASS    API is reachable              |
2026-07-30T23:19:18Z INF |                                                                                     |
2026-07-30T23:19:18Z INF |  SUMMARY: Environment is healthy. cloudflared will use 'quic' as primary protocol.  |
2026-07-30T23:19:18Z INF +-------------------------------------------------------------------------------------+
2026-07-30T23:19:18Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f status=pass target=region1.v2.argotunnel.com
2026-07-30T23:19:18Z INF precheck component="DNS Resolution" details="DNS Resolved successfully" run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f status=pass target=region2.v2.argotunnel.com
2026-07-30T23:19:18Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f status=pass target=region1.v2.argotunnel.com
2026-07-30T23:19:18Z INF precheck component="UDP Connectivity" details="QUIC connection successful" run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f status=pass target=region2.v2.argotunnel.com
2026-07-30T23:19:18Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f status=pass target=region1.v2.argotunnel.com
2026-07-30T23:19:18Z INF precheck component="TCP Connectivity" details="HTTP/2 connection successful" run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f status=pass target=region2.v2.argotunnel.com
2026-07-30T23:19:18Z INF precheck component="Cloudflare API" details="API is reachable" run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f status=pass target=api.cloudflare.com:443
2026-07-30T23:19:18Z INF precheck complete hard_fail=false run_id=a695e35e-0d4b-4e73-9ccd-10ec0604303f suggested_protocol=quic